# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#

#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
# 4V48J9GGFV


# skip_waiting_for_build_processing  ??

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


# yyvc-xsvn-iazg-yqqm   password itunes

default_platform(:ios)

platform :ios do
	
  before_all do
    ENV["FASTLANE_DONT_STORE_PASSWORD"] = "1"
    ENV["FASTLANE_USER"] = "ios-legacy-publishing@kolibel.tech"
    ENV["FASTLANE_PASSWORD"] = '9Q7MISKAAJOK4w98'
    ENV["SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER"] = "+380672665448"
    ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "zqas-gjpl-xvgz-ijzd"
#    ENV["DEVELOPER_DIR"] = "/Users/viktornesmieianov/Soft/Xcode10.2.app/Contents/Developer"
#    ENV["DEVELOPER_DIR"] = "/Users/viktornesmieianov/Soft/Xcode11.2.app/Contents/Developer"    
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    changelog = File.read("Changelog.txt")
#    puts changelog
#    changelog = prompt(
#        text: "Changelog: ",
#        multi_line_end_keyword: "END"
#    )
  	build_app(scheme: "iOSHelloWorld",
  	          include_bitcode: true)
#  	upload_to_testflight
  	upload_to_testflight(changelog: changelog)
  	pilot(skip_waiting_for_build_processing:true)
  end
  # lane :screenshots do
  #   capture_screenshots(scheme: "Maps")
  # end
end
